# Generated by Django 5.0.3 on 2024-03-17 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
