# Generated by Django 5.0.3 on 2024-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_options_remove_portfolio_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, upload_to='dir_on_cloudinary'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
